
---
- host: all
  task:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install Nginx for Debian 
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"


    - name: Install Nginx for RedHat
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    
    - name: start nginx service and enable for Debian 
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    -  name: start nginx service and enable for RedHat
       ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
       when: ansible_os_family == "RedHat""
